### ISSUE TITLE
Block validation errors = Proof of work too weak

### ISSUE THREAD

**Issue by zhmrab** [forknote/forknote#87]
Running into the proof of work issue again, generated daemons and forknote daemons are both not syncing to the network anymore, 
This only happens when pool mining, solo mining so far hasn't produced any block with "proof of work too weak"

How could we fix the block validation so that the syncing can resume? 

Thanks

**Comment by pmitchev** [comment]
Do you have both forknote and generated daemons on your network?  I found an unupdated code on forknote.net, which makes the generated daemons not to include the required extensions for zawy difficulty:

`    "extensions": [
        "core/bytecoin.json",
        "print-genesis-tx.json",
        "versionized-parameters.json",
        "zawy-difficulty-algorithm.json"
    ]`

Also, make sure you use ZAWY_DIFFICULTY_BLOCK_INDEX and other options for Zawy diff, because the previews options are deprecated

**Comment by zhmrab** [comment]
@pmitchev I use basic forknote (--config-file etc..) on seeds and generated daemons locally on my computer, I did not include ZAWY in my forknote.conf, nor did I included it in the extensions when generating the daemons bc I saw other people having issues with it... 

Is this normal that this is happening even though I am not using zawy at all?

**Comment by zhmrab** [comment]
@pmitchev it is working again thank you for the help, much appreciated, closing this

**Comment by PandaDudz** [comment]
@zhmrab can you explain how to configure zawy properly

**Comment by inzider** [comment]
@zhmrab Hi, I am running on the same issue, can you let me know what modif you did apply.
