### ISSUE TITLE
Seed nodes PROBLEM

### ISSUE THREAD

**Issue by PandaDudz** [forknote/forknote#90]
Hello everyone,

I have a problem i cant solve for quite some time now. I wanted to find solution from previous issue posts but wast able to, so im forced to ask help from you and i hope you are willing to help.

Anyway, just to make sure, i have one aws lightsail server for daemon and 2 aws ec2 instances for seed nodes. When i start the daemon i get error **Connection to 52.47.165.125:48923 failed: TcpConnector::connect, connection failed** and same for the other seed node... and seed node conf file is configured as shown on offical forknote site... **p2p-bind-port=8080 and rpc-bind-port=8081   seed-node=52.47.165.125:48923
seed-node=52.47.165.125:48923**

Starting seed nodes i get error **Connection to 52.47.165.125:8080 timed out**

Can you help?
If you want to help you can also contact me on mail pandadud6@gmail.com

Thank you

**Comment by PandaDudz** [comment]
[
![1518535007082114039868](https://user-images.githubusercontent.com/6645217/36157129-6686d640-10d9-11e8-8d17-24f9e0152afe.jpg)
](url)

Seed node 


And here is daemon

![15185351600111241117190](https://user-images.githubusercontent.com/6645217/36157270-b7424b32-10d9-11e8-9b3a-7a28e02d3a11.jpg)

**Comment by PandaDudz** [comment]
Here is the seed node config file
![15185352932632125207190](https://user-images.githubusercontent.com/6645217/36157455-1f8cbf56-10da-11e8-9fd4-462a66719006.jpg)

**Comment by michaellu88** [comment]
try setting p2p-bind-port=48923 and rpc-bind-port=48924
seed-node=52.47.165.125:48923
seed-node=52.47.165.125:48923

try open up 48923 and 48924 port on AWS ec2 server (there is a video on youtube how to do that)

**Comment by spotme-main** [comment]
So all nodes run the daemon just so we have termonology right.   In your case, i think you are telling me the daemon is the client-node you are trying to connect to the seed nodes.

There is no need to change configuration when it comes to ports for your seed-nodes or client-nodes unless you are running other services on your clients.

I was going to say.. it looks like the p2p ports you've specified are closed.   if you want to run seed nodes on 8080.. then your clients are going to try to connect to seed nodes on port 8080.  The seed nodes look like they are starting on 8080..

use an online port scanner to verify the port is open..
http://www.t1shopper.com/tools/port-scan/

Other than that.. I wouldnt use 8080..   I would use a random one like you did 48923..  less chance of conflicts with other port traffic.  just do a quick search before you select a port to ensure some other program that tends to get blocked by ISP's doesnt use that port.  You dont want all those people running clients having problems connecting because of issues you can't control (and could avoid)

**Comment by PandaDudz** [comment]
Thank you both both answers solved my problem. Except now i have simplewallet error :D @michaellu88 @spotme-main
